apiVersion: v2
name: kps
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 45.27.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-blackbox-exporter
    version: 7.8.0
    repository: https://prometheus-community.github.io/helm-charts
