apiVersion: v2
name: kps
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 80.13.3
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-blackbox-exporter
    version: 11.7.0
    repository: https://prometheus-community.github.io/helm-charts
