---
- name: k8s cluster init
  hosts: all
  gather_facts: true

  roles:
    - { role: k8s/cluster_init }

- name: k8s apps
  hosts: localhost
  gather_facts: false

  roles:
    - { role: k8s_apps/argocd }
    - { role: k8s_apps/vault_secrets }
